version: '2.1'

services:

  db:
    container_name: db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  graphql:
    container_name: graphql
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - DATABASE_URL=db
      - DATABASE_NAME="graphql"
      - DATABASE_PORT="5432"
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - db