# Generated by Django 2.0 on 2017-12-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0002_call_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_unify',
            name='ext',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
