# Generated by Django 2.0 on 2017-12-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0008_auto_20171229_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_unify',
            name='agent_ot',
        ),
        migrations.RemoveField(
            model_name='event_ot',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='event_ot',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_ot',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_unify',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='agent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='ext',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ot_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ot_userdisplayname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ot_userloginname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_login',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone_state',
            field=models.CharField(blank=True, default='available', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='graphqlendpoint.Agent'),
        ),
        migrations.AddField(
            model_name='event',
            name='creationdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ot_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='graphqlendpoint.Agent'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='transferhistory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='primaryagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calls', to='graphqlendpoint.Agent'),
        ),
        migrations.AlterField(
            model_name='call',
            name='secondaryagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calls_alt', to='graphqlendpoint.Agent'),
        ),
        migrations.DeleteModel(
            name='Agent_ot',
        ),
        migrations.DeleteModel(
            name='Agent_unify',
        ),
        migrations.DeleteModel(
            name='Event_ot',
        ),
    ]
