# Generated by Django 2.0 on 2017-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0009_auto_20171229_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
