# Generated by Django 2.0 on 2017-12-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0010_event_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('predecessor', models.IntegerField(blank=True, null=True)),
                ('searchcode', models.CharField(max_length=200, null=True)),
                ('ot_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(null=True)),
                ('title', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('solution', models.CharField(max_length=200, null=True)),
                ('ot_id', models.CharField(max_length=200, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to='graphqlendpoint.Agent')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='graphqlendpoint.Category')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_responsible', to='graphqlendpoint.Agent')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_applicant', to='graphqlendpoint.Agent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_responsible', to='graphqlendpoint.Agent'),
        ),
        migrations.AddField(
            model_name='call',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calls_alt', to='graphqlendpoint.Ticket'),
        ),
    ]
