# Generated by Django 2.0 on 2017-12-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0012_loggedinuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='graphqlendpoint.Call')),
            ],
        ),
    ]
