# Generated by Django 2.0.1 on 2018-01-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0014_auto_20171231_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='name',
        ),
        migrations.AlterField(
            model_name='call',
            name='primaryagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='call', to='graphqlendpoint.Agent'),
        ),
    ]
