# Generated by Django 2.0.1 on 2018-01-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0015_auto_20180103_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='secondaryagent',
        ),
        migrations.RemoveField(
            model_name='call',
            name='ticket',
        ),
        migrations.AddField(
            model_name='call',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='call', to='graphqlendpoint.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='graphqlendpoint.Ticket'),
        ),
        migrations.AlterField(
            model_name='call',
            name='primaryagent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='call_for_agent', to='graphqlendpoint.Agent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_tickets', to='graphqlendpoint.Category'),
        ),
    ]
