# Generated by Django 2.0.1 on 2018-01-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0016_auto_20180103_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='current_agent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_call', to='graphqlendpoint.Agent'),
        ),
    ]
