# Generated by Django 2.0.1 on 2018-01-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0018_auto_20180104_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='primaryagent',
        ),
    ]
