# Generated by Django 2.0.1 on 2018-01-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0019_remove_call_primaryagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='current_agent',
        ),
        migrations.RemoveField(
            model_name='call',
            name='event',
        ),
        migrations.AddField(
            model_name='agent',
            name='current_call',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_agent', to='graphqlendpoint.Call'),
        ),
        migrations.AddField(
            model_name='event',
            name='call',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='graphqlendpoint.Call'),
        ),
    ]
