# Generated by Django 2.0 on 2017-12-27 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='userimage')),
            ],
        ),
        migrations.CreateModel(
            name='Agent_ot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userloginname', models.CharField(max_length=200, null=True)),
                ('userdisplayname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('is_helpdesk', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('ot_id', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, default='available', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agent_unify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ext', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='available', max_length=200)),
                ('agent_ot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='graphqlendpoint.Agent_ot')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucid', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('call_type', models.CharField(max_length=200, null=True)),
                ('start', models.DateTimeField(max_length=200, null=True)),
                ('end', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('isContactCenterCall', models.BooleanField(default=False)),
                ('history', models.CharField(max_length=600, null=True)),
                ('primaryagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='graphqlendpoint.Agent')),
                ('secondaryagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls_alt', to='graphqlendpoint.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_ot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationDate', models.DateTimeField(null=True)),
                ('Eventtype', models.CharField(max_length=200, null=True)),
                ('ot_id', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('transferhistory', models.CharField(max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='graphqlendpoint.Agent_ot')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='graphqlendpoint.Agent_ot')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_ot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='graphqlendpoint.Agent_ot'),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_unify',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='graphqlendpoint.Agent_unify'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
