# Generated by Django 2.0 on 2017-12-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0003_auto_20171228_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_unify',
            name='agent_ot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='graphqlendpoint.Agent_ot'),
        ),
    ]
