# Generated by Django 2.0 on 2017-12-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphqlendpoint', '0006_auto_20171228_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(max_length=200)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphqlendpoint.Call')),
            ],
        ),
    ]
